version: "{build}"
branches:
  except:
    - gh-pages
install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install
  - npm run build
build: off
deploy: off
environment:
  matrix:
    - nodejs_version: 8
artifacts:
  - path: desktop-natori-ssp.zip
    name: desktop-natori-ssp.zip
cache:
  - ssp/ghost/desktop-natori/ghost/master/voices
